"""empty message

Revision ID: 757af51c21c1
Revises: 
Create Date: 2023-10-23 05:08:12.324384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '757af51c21c1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commCode',
    sa.Column('codeGrp', sa.String(), nullable=False),
    sa.Column('codeGrpNm', sa.String(), nullable=True),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('codeNm', sa.String(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('regDt', sa.DateTime(), nullable=True),
    sa.Column('updDt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('codeGrp', 'code')
    )
    op.create_table('scheManager',
    sa.Column('seq', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sid', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('seq')
    )
    op.create_table('scheduleHistory',
    sa.Column('seq', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sid', sa.String(), nullable=True),
    sa.Column('scheDt', sa.String(), nullable=True),
    sa.Column('phnNum', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('regDt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('seq'),
    sa.UniqueConstraint('sid', 'scheDt', 'phnNum', name='scheduleHistory_unique_commit')
    )
    op.create_table('scheduleManager',
    sa.Column('seq', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sid', sa.String(), nullable=True),
    sa.Column('scheDt', sa.String(), nullable=True),
    sa.Column('phnNum', sa.String(), nullable=True),
    sa.Column('stat', sa.String(), nullable=True),
    sa.Column('regDt', sa.DateTime(), nullable=True),
    sa.Column('updDt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('seq'),
    sa.UniqueConstraint('sid', 'scheDt', 'phnNum', name='scheduleManager_unique_commit')
    )
    op.create_table('scheduleState',
    sa.Column('seq', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scheDttm', sa.String(), nullable=True),
    sa.Column('stat', sa.String(), nullable=True),
    sa.Column('regDt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('seq')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scheduleState')
    op.drop_table('scheduleManager')
    op.drop_table('scheduleHistory')
    op.drop_table('scheManager')
    op.drop_table('commCode')
    # ### end Alembic commands ###
