"""empty message

Revision ID: f7de24bf5bd8
Revises: 757af51c21c1
Create Date: 2023-10-23 05:09:46.383969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7de24bf5bd8'
down_revision: Union[str, None] = '757af51c21c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scheManager')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheManager',
    sa.Column('seq', sa.INTEGER(), nullable=False),
    sa.Column('sid', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('seq')
    )
    # ### end Alembic commands ###
